# Generated by Django 5.2.1 on 2025-06-25 09:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=100)),
                ('facility_type', models.CharField(max_length=50)),
                ('license_number', models.CharField(max_length=100)),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('province', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('location_coordinates', models.CharField(blank=True, help_text='Latitude,Longitude format', max_length=100, null=True)),
                ('contact_person', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('staff_capacity', models.CharField(blank=True, max_length=50, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=False)),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('O-', 'O-')], max_length=3)),
                ('province', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('donation_time', models.CharField(max_length=10)),
                ('additional_info', models.TextField(blank=True)),
                ('has_donated_before', models.BooleanField(default=False)),
                ('last_donation_before_registration', models.DateField(blank=True, null=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('reset_token', models.CharField(blank=True, max_length=64, null=True)),
                ('date_joined', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProgressTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(default=django.utils.timezone.now)),
                ('target_donations', models.PositiveIntegerField()),
                ('actual_donations', models.PositiveIntegerField(default=0)),
                ('goal_met', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UrgencyBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DonationDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bload_donor_app.collector')),
            ],
        ),
        migrations.CreateModel(
            name='DonationAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('selected_center', models.CharField(max_length=255)),
                ('confirmed', models.BooleanField(default=False)),
                ('donor_coordinates', models.CharField(blank=True, max_length=100, null=True)),
                ('collector_coordinates', models.CharField(blank=True, max_length=100, null=True)),
                ('has_donated_before', models.BooleanField(default=False)),
                ('collector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bload_donor_app.collector')),
                ('drive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bload_donor_app.donationdrive')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='bload_donor_app.donor')),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=10)),
                ('donors', models.ManyToManyField(blank=True, related_name='rewards', to='bload_donor_app.donor')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.TextField()),
                ('role', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bload_donor_app.donor')),
            ],
        ),
    ]
