# Generated by Django 5.2.1 on 2025-06-22 16:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bload_donor_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='date_joined',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
