# Generated by Django 5.2.1 on 2025-06-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bload_donor_app', '0002_donor_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
